services:
  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/config:/etc/prometheus
  grafana:
    image: grafana/grafana:11.6.16
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
