# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    # not useful
    - exhaustivestruct
    - exhaustruct

linters-settings:
  gci:
    local-prefixes: github.com/utkuozdemir/nvidia_gpu_exporter
  goimports:
    local-prefixes: github.com/utkuozdemir/nvidia_gpu_exporter
  goconst:
    ignore-tests: true
