# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    # deprecated:
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - scopelint
    # not useful
    - exhaustruct
    # TODO: consider enabling:
#    - testpackage

linters-settings:
  gci:
    local-prefixes: github.com/utkuozdemir/nvidia_gpu_exporter
  goimports:
    local-prefixes: github.com/utkuozdemir/nvidia_gpu_exporter
  goconst:
    ignore-tests: true
