# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    # not useful
    - exhaustruct
    - err113

linters-settings:
  gci:
    sections:
        - standard
        - default
        - localmodule
  goimports:
    local-prefixes: github.com/utkuozdemir/nvidia_gpu_exporter
  goconst:
    ignore-tests: true
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
