# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    # breaking things: https://github.com/atc0005/go-ci/issues/1024
    - depguard
    # not useful
    - exhaustivestruct
    - exhaustruct
    - goerr113

linters-settings:
  gci:
    sections:
        - standard
        - default
        - prefix(github.com/utkuozdemir/nvidia_gpu_exporter)
        - blank
        - dot
        - alias
  goimports:
    local-prefixes: github.com/utkuozdemir/nvidia_gpu_exporter
  goconst:
    ignore-tests: true
