---
before:
  hooks:
    - go mod download

builds:
  - id: nvidia_gpu_exporter
    main: ./cmd/nvidia_gpu_exporter
    binary: nvidia_gpu_exporter
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.Commit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    goarm:
     - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: "386"

archives:
  - id: nvidia_gpu_exporter-archive
    rlcp: true
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    builds:
      - nvidia_gpu_exporter
    format_overrides:
      - goos: windows
        format: zip
    files: 
      - LICENSE

nfpms:
  - id: nvidia_gpu_exporter
    package_name: nvidia-gpu-exporter
    bindir: /usr/bin
    vendor: Utku Ozdemir
    homepage: https://github.com/utkuozdemir/nvidia_gpu_exporter
    license: MIT
    maintainer: Utku Ozdemir <utkuozdemir@gmail.com>
    section: misc
    description: |-
      Nvidia GPU exporter for prometheus.
      This is a simple exporter that uses `nvidia-smi(.exe)` binary to collect, 
      parse and export metrics.
    formats:
      - deb
      - rpm
    contents:
      - src: ./systemd/nvidia_gpu_exporter.service
        dst: /usr/lib/systemd/system/nvidia_gpu_exporter.service
        file_info:
          owner: root
          group: root
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/nvidia-gpu-exporter/copyright
        file_info:
          owner: root
          group: root
          mode: 0644
    scripts:
      preinstall: scripts/pre-install.sh
      postinstall: scripts/post-install.sh
      preremove: scripts/pre-remove.sh
      postremove: scripts/post-remove.sh
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
        - no-manual-page
        # Probably won't be implemented: https://github.com/goreleaser/nfpm/issues/15#issuecomment-830816661
        - maintainer-script-calls-systemctl

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^build(\(.+\))?:'
      - '^chore(\(.+\))?:'
      - '^cd(\(.+\))?:'
      - '^ci(\(.+\))?:'
      - '^cicd(\(.+\))?:'
      - '^docker(\(.+\))?:'
      - '^docs(\(.+\))?:'
      - '^refactor(\(.+\))?:'
      - '^test(\(.+\))?:'
      - Merge pull request
      - Merge branch
      - go mod tidy

dockers:
  - image_templates:
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates:
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-arm64
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm64
  - image_templates:
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-armv7
    use: buildx
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm/v7

docker_manifests:
  - name_template: docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}
    image_templates:
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-amd64
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-arm64
      - docker.io/utkuozdemir/nvidia_gpu_exporter:{{ .Version }}-armv7

# To test docker image push, uncomment the following and run
# goreleaser release --skip-validate --rm-dist --debug
#release:
#  disable: true

scoop:
  bucket:
    owner: utkuozdemir
    name: scoop_nvidia_gpu_exporter
    token: "{{ .Env.PRIVATE_ACCESS_TOKEN }}"
  commit_author:
    name: Utku Ozdemir
    email: utkuozdemir@gmail.com
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: https://github.com/utkuozdemir/nvidia_gpu_exporter
  description: Nvidia GPU exporter for prometheus using nvidia-smi binary
  license: MIT
