version: "3"

tasks:
  fmt:
    desc: format code
    cmds:
      - go mod tidy
      - golangci-lint run --fix ./...
      - shfmt -l -i 2 -ci -sr -w .

  lint:
    desc: lint code
    cmds:
      - go mod tidy --diff
      - golangci-lint run ./...
      - markdownlint **/*.md
      - shellcheck **/*.sh
      - shfmt -l -i 2 -ci -sr .
      - goreleaser check

  release:
    desc: release
    vars:
      NEXT:
        sh: svu next
    cmds:
      - git tag -a {{.NEXT}} -m "Release {{.NEXT}}"
      - echo {{.NEXT}}
      - git push origin {{.NEXT}}
