version: "3"

tasks:
  fmt:
    desc: format code
    cmds:
      - go mod tidy
      - markdownlint --fix **/*.md
      - shfmt --write **/*.sh
      - golangci-lint run --fix ./...

  lint:
    desc: lint code
    cmds:
      - go mod tidy && git diff --no-patch --exit-code go.mod go.sum
      - golangci-lint run ./...
      - markdownlint **/*.md
      - shellcheck **/*.sh
      - shfmt --diff **/*.sh
      - goreleaser check

  release:
    desc: release
    vars:
      NEXT:
        sh: svu next
    cmds:
      - git tag -a {{.NEXT}} -m "Release {{.NEXT}}"
      - echo {{.NEXT}}
      - git push origin {{.NEXT}}
