{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "nvidia-gpu-exporter.fullname" . }}
  labels:
    {{- include "nvidia-gpu-exporter.labels" . | nindent 4 }}
  {{- with .Values.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podMetricsEndpoints:
    - port: http
      path: {{ .Values.telemetryPath }}
      {{- with .Values.podMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  selector:
    matchLabels:
      {{- include "nvidia-gpu-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
