---
name: release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          # to be able to generate the full changelog:
          # https://github.com/goreleaser/goreleaser-action/issues/56#issuecomment-568718162
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: go.mod
      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: utkuozdemir
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v4.4.0
        with:
          # renovate: depName=goreleaser/goreleaser datasource=github-releases
          version: v1.20.0
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_ACCESS_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows_exporter_binaries
          path: |
            dist/nvidia_gpu_exporter_windows_*/
            dist/checksums.txt
  release-msi:
    needs: release
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: go.mod

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows_exporter_binaries
          path: .\dist\

      - name: Build Release Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $ErrorActionPreference = "Stop"
          $TagName = $env:GITHUB_REF -replace 'refs/tags/', ''
          # The MSI version is not semver compliant, so just take the numerical parts
          $MSIVersion = $TagName -replace '^v?([0-9\.]+).*$','$1'
          Get-ChildItem -Path .\dist\nvidia_gpu_exporter_windows_* | ForEach-Object {
            $Arch = ($_ -split "nvidia_gpu_exporter_windows_")[1]
            Write-Verbose "Building windows_exporter ${MSIVersion} msi for $Arch"
            .\install\build.ps1 -PathToExecutable ".\dist\nvidia_gpu_exporter_windows_${Arch}/nvidia_gpu_exporter.exe" -Version "${MSIVersion}" -Arch "$Arch"
            Move-Item ".\install\Output\nvidia_gpu_exporter_${MSIVersion}_${Arch}.msi" .\dist\
          }

      - name: Display structure of downloaded files
        run: ls -R .\dist\

      - name: Generate checksums for msi
        run: |
          Get-FileHash -Algorithm SHA256 -Path .\dist\*.msi | ForEach-Object {
            $filename = Split-Path -Leaf $_.Path
            $hash = $_.Hash
            Write-Output "$hash  $filename" |  Add-Content -Path ".\dist\checksums.txt" -Encoding UTF8
          }

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $TagName = $env:GITHUB_REF -replace 'refs/tags/', ''
          Get-ChildItem -Path .\dist\* -Include @('nvidia_gpu_exporter*.msi', 'checksums.txt') | Foreach-Object {gh release upload --clobber $TagName $_}