---
name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          # to be able to generate the full changelog:
          # https://github.com/goreleaser/goreleaser-action/issues/56#issuecomment-568718162
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2.1.4
        with:
          # renovate: go
          go-version: 1.17
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: utkuozdemir
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.0
        with:
          # renovate: goreleaser
          version: v1.0.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_ACCESS_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
